"""employers_lmia, entities, ingest runs and rejects

Revision ID: 4355e3d3505d
Revises:
Create Date: 2026-09-11 21:08:56.905417

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Must precede the GIN indexes below, which use gin_trgm_ops. pg_trgm also
    # backs the similarity comparisons the future fuzzy employer-matching pass
    # will need, so it is a dependency of the schema rather than an add-on.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employer_entities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("employer_key", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("match_method", sa.String(length=16), nullable=False),
        sa.Column("variant_count", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_quarter", sa.String(length=6), nullable=True),
        sa.Column("last_seen_quarter", sa.String(length=6), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employer_key"),
    )
    op.create_index(
        "ix_employer_entities_name_trgm",
        "employer_entities",
        ["canonical_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_format", sa.String(length=8), nullable=False),
        sa.Column("reader", sa.String(length=32), nullable=True),
        sa.Column("quarter", sa.String(length=6), nullable=True),
        sa.Column("banner", sa.Text(), nullable=True),
        sa.Column("noc_version", sa.String(length=4), nullable=True),
        sa.Column("header_row", sa.Integer(), nullable=True),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("rows_loaded", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("anomalies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unmapped_columns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_runs_quarter"), "ingest_runs", ["quarter"], unique=False)
    op.create_index(
        op.f("ix_ingest_runs_source_file"), "ingest_runs", ["source_file"], unique=False
    )
    op.create_index(op.f("ix_ingest_runs_status"), "ingest_runs", ["status"], unique=False)
    op.create_table(
        "employers_lmia",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("ingest_run_id", sa.BigInteger(), nullable=True),
        sa.Column("quarter", sa.String(length=6), nullable=False),
        sa.Column("employer_raw", sa.Text(), nullable=False),
        sa.Column("employer_key", sa.Text(), nullable=True),
        sa.Column("employer_id", sa.BigInteger(), nullable=True),
        sa.Column("province_raw", sa.Text(), nullable=True),
        sa.Column("province", sa.String(length=2), nullable=True),
        sa.Column("location_scope", sa.String(length=16), nullable=False),
        sa.Column("address_raw", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.String(length=7), nullable=True),
        sa.Column("postal_fsa", sa.String(length=3), nullable=True),
        sa.Column("postal_truncated", sa.Boolean(), nullable=False),
        sa.Column("program_stream_raw", sa.Text(), nullable=True),
        sa.Column("program_stream", sa.Text(), nullable=True),
        sa.Column("is_pr_only", sa.Boolean(), nullable=False),
        sa.Column("incorporate_status", sa.Text(), nullable=True),
        sa.Column("occupation_raw", sa.Text(), nullable=True),
        sa.Column("noc_code", sa.String(length=8), nullable=True),
        sa.Column("noc_title", sa.Text(), nullable=True),
        sa.Column("noc_version", sa.String(length=4), nullable=True),
        sa.Column("approved_lmias", sa.Integer(), nullable=True),
        sa.Column("approved_lmias_raw", sa.Text(), nullable=True),
        sa.Column("approved_positions", sa.Integer(), nullable=True),
        sa.Column("approved_positions_raw", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["employer_id"], ["employer_entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ingest_run_id"], ["ingest_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_file", "line_no", name="uq_employers_lmia_source_line"),
    )
    op.create_index(
        op.f("ix_employers_lmia_employer_id"), "employers_lmia", ["employer_id"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_employer_key"), "employers_lmia", ["employer_key"], unique=False
    )
    op.create_index(
        "ix_employers_lmia_employer_trgm",
        "employers_lmia",
        ["employer_raw"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"employer_raw": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_employers_lmia_incorporate_status"),
        "employers_lmia",
        ["incorporate_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employers_lmia_is_pr_only"), "employers_lmia", ["is_pr_only"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_location_scope"), "employers_lmia", ["location_scope"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_noc_code"), "employers_lmia", ["noc_code"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_noc_version"), "employers_lmia", ["noc_version"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_postal_fsa"), "employers_lmia", ["postal_fsa"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_program_stream"), "employers_lmia", ["program_stream"], unique=False
    )
    op.create_index(
        op.f("ix_employers_lmia_province"), "employers_lmia", ["province"], unique=False
    )
    op.create_index(op.f("ix_employers_lmia_quarter"), "employers_lmia", ["quarter"], unique=False)
    op.create_index(
        "ix_employers_lmia_quarter_noc", "employers_lmia", ["quarter", "noc_code"], unique=False
    )
    op.create_index(
        "ix_employers_lmia_quarter_province",
        "employers_lmia",
        ["quarter", "province"],
        unique=False,
    )
    op.create_index(
        "ix_employers_lmia_quarter_stream",
        "employers_lmia",
        ["quarter", "program_stream"],
        unique=False,
    )
    op.create_table(
        "ingest_rejects",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ingest_run_id", sa.BigInteger(), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("raw_row", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["ingest_run_id"], ["ingest_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingest_rejects_ingest_run_id"), "ingest_rejects", ["ingest_run_id"], unique=False
    )
    op.create_index(op.f("ix_ingest_rejects_reason"), "ingest_rejects", ["reason"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingest_rejects_reason"), table_name="ingest_rejects")
    op.drop_index(op.f("ix_ingest_rejects_ingest_run_id"), table_name="ingest_rejects")
    op.drop_table("ingest_rejects")
    op.drop_index("ix_employers_lmia_quarter_stream", table_name="employers_lmia")
    op.drop_index("ix_employers_lmia_quarter_province", table_name="employers_lmia")
    op.drop_index("ix_employers_lmia_quarter_noc", table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_quarter"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_province"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_program_stream"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_postal_fsa"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_noc_version"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_noc_code"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_location_scope"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_is_pr_only"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_incorporate_status"), table_name="employers_lmia")
    op.drop_index(
        "ix_employers_lmia_employer_trgm",
        table_name="employers_lmia",
        postgresql_using="gin",
        postgresql_ops={"employer_raw": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_employers_lmia_employer_key"), table_name="employers_lmia")
    op.drop_index(op.f("ix_employers_lmia_employer_id"), table_name="employers_lmia")
    op.drop_table("employers_lmia")
    op.drop_index(op.f("ix_ingest_runs_status"), table_name="ingest_runs")
    op.drop_index(op.f("ix_ingest_runs_source_file"), table_name="ingest_runs")
    op.drop_index(op.f("ix_ingest_runs_quarter"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index(
        "ix_employer_entities_name_trgm",
        table_name="employer_entities",
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.drop_table("employer_entities")
    # ### end Alembic commands ###
