"""split employer legal entity from trade brand

Revision ID: d994e3210676
Revises: 0001_initial
Create Date: 2026-09-11 22:05:45.987620

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_brand_split"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employers_lmia", sa.Column("trade_name_raw", sa.Text(), nullable=True))
    op.add_column("employers_lmia", sa.Column("brand_key", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_employers_lmia_brand_key"), "employers_lmia", ["brand_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employers_lmia_brand_key"), table_name="employers_lmia")
    op.drop_column("employers_lmia", "brand_key")
    op.drop_column("employers_lmia", "trade_name_raw")
    # ### end Alembic commands ###
